# Generated by Django 5.2.8 on 2025-11-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='', help_text='External image URL (e.g., Imgur)', max_length=500),
            preserve_default=False,
        ),
    ]
