# Generated by Django 5.2.8 on 2025-12-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, db_column='Ingredients', help_text='Active ingredients in the medication'),
        ),
    ]
