# Generated by Django 5.2.8 on 2025-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_usage',
            field=models.TextField(blank=True, help_text='How to use this medication'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Active ingredients in the medication'),
        ),
    ]
